spring.application.name=ssafy_5_Trip

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.thymeleaf.enabled=false

#mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ssafy?serverTimezone=Asia/Seoul
spring.datasource.username=ssafy
spring.datasource.password=ssafy
#???? sql ???
spring.jpa.properties.hibernate.show_sql=true
#sql ??? ?? ???
spring.jpa.properties.hibernate.format_sql=true
#db ??? ??. ?? ??? ?? ? ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#iamport
imp.code='imp78814812'
imp.api.key='7066342360463017'
imp.api.secretkey='iWy2KaLeZG1v5wRiQS6lcQVFsOiTuPj4o70CmLMiinIP49aCBsKfheaf0IbuOQqKRjj5yMFxfHb28sx0'